# Generated by Django 2.2.2 on 2019-06-07 19:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('login', models.CharField(max_length=40)),
                ('user_id', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('text', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comm_bot.User')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='AnonymousUser', max_length=20)),
                ('answer_to', models.IntegerField(default=0)),
                ('answers', models.TextField(default=b'\x80\x03]q\x00.')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(default=datetime.datetime(2019, 6, 7, 19, 49, 35, 42122, tzinfo=utc))),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comm_bot.Thread')),
            ],
        ),
    ]
