# Generated by Django 2.2.2 on 2019-06-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comm_bot', '0002_auto_20190619_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(default='пирожочек'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(default='start', max_length=40),
        ),
    ]
